# Generated by Django 4.1.2 on 2022-10-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_creator',
            new_name='user',
        ),
    ]
