# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_description', models.CharField(max_length=100, verbose_name='Тайтл прайса')),
                ('pc_value', models.CharField(max_length=20, verbose_name='Цены')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(max_length=100, verbose_name='Услуга')),
                ('pt_old_price', models.CharField(max_length=50, verbose_name='Старая цена')),
                ('pt_new_price', models.CharField(max_length=20, verbose_name='Новая цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
