# Generated by Django 4.1.1 on 2022-09-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tele_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele_token', models.CharField(max_length=100, verbose_name='Токен бота')),
                ('tele_chat_id', models.CharField(max_length=20, verbose_name='Чат айди бота')),
                ('tele_text', models.TextField(verbose_name='Текст бота')),
            ],
            options={
                'verbose_name': 'Настройка бота',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
